### ISSUE TITLE
Console error when open Crafting Manager (AE block)

### ISSUE THREAD

**Issue by KorewaLidesu** [Domaman202/LogisticsBridge#22]
```[16:15:22] [Client thread/INFO] [STDERR]: [logisticspipes.proxy.MainProxy:sendPacketToPlayer:171]: sendPacketToPlayer called clientside !
java.lang.Exception
	at logisticspipes.proxy.MainProxy.sendPacketToPlayer(MainProxy.java:172)
	at com.tom.logisticsbridge.tileentity.TileEntityCraftingManager.openGui(TileEntityCraftingManager.java:413)
	at com.tom.logisticsbridge.block.BlockCraftingManager.func_180639_a(BlockCraftingManager.java:32)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187099_a(PlayerControllerMP.java:423)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1579)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2254)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2020)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1808)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
```

**Comment by Domaman202** [comment]
да бля....

**Comment by Domaman202** [comment]
только пофиксил одно - падает другое :D

**Comment by KorewaLidesu** [comment]
> только пофиксил одно - падает другое :D

This is from the past and this is console error, no crash.

**Comment by Domaman202** [comment]
ok

**Comment by Domaman202** [comment]
and the message before that "sendPacketToPlayer called the client!" was also displayed?

**Comment by KorewaLidesu** [comment]
```
[14:21:25] [Client thread/INFO] [STDERR]: [logisticspipes.proxy.MainProxy:sendPacketToPlayer:171]: sendPacketToPlayer called clientside !
java.lang.Exception
	at logisticspipes.proxy.MainProxy.sendPacketToPlayer(MainProxy.java:172)
	at com.tom.logisticsbridge.tileentity.TileEntityCraftingManager.openGui(TileEntityCraftingManager.java:414)
	at com.tom.logisticsbridge.block.BlockCraftingManager.func_180639_a(BlockCraftingManager.java:32)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187099_a(PlayerControllerMP.java:423)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1579)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2254)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2020)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1808)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
```
